WebbiSkools.QuizManager.Web/Controllers/QuizzesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
using WebbiSkools.QuizManager.Web.Data;
using WebbiSkools.QuizManager.Web.Models;

namespace WebbiSkools.QuizManager.Web.Controllers
{
    [Authorize]
    public class QuizzesController : Controller
    {
        private readonly QuizManagerContext _context;

        public QuizzesController(QuizManagerContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View("Index", await _context.Quizzes.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quiz = await _context.Quizzes
                .Include(q => q.Questions)
                .ThenInclude(q => q.Answers)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (quiz == null)
            {
                return NotFound();
            }

            return View(quiz);
        }

        [Authorize(Roles = "Edit")]
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Edit")]
        public async Task<IActionResult> Create(Quiz quiz)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(quiz);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View("Create", quiz);
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("Unable to save changes.", ex, null);
            }

            return View("Create", quiz);
        }

        [Authorize(Roles = "Edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quiz = await _context.Quizzes
                .Include(q => q.Questions)
                .ThenInclude(q => q.Answers)
                .FirstOrDefaultAsync(q => q.Id == id);

            if (quiz == null)
            {
                return NotFound();
            }
            return View("Edit", quiz);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Edit")]
        public async Task<IActionResult> Edit(int id, Quiz quiz)
        {
            if (id != quiz.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var quizToUpdate = await _context.Quizzes
                    .Include(q => q.Questions)
                    .ThenInclude(q => q.Answers)
                    .FirstOrDefaultAsync(q => q.Id == id);

                if (await TryUpdateModelAsync<Quiz>(
                    quizToUpdate,
                    ""))
                {
                    try
                    {
                        await _context.SaveChangesAsync();

                        return RedirectToAction(nameof(Index));
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!QuizExists(quiz.Id))
                        {
                            return NotFound();
                        }

                        ModelState.AddModelError("", "Unable to save changes. Please try again.");
                    }
                }
            }

            return View("Edit", quiz);
        }

        [Authorize(Roles = "Edit")]
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quiz = await _context.Quizzes
                .Include(q => q.Questions)
                .ThenInclude(q => q.Answers)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (quiz == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Delete failed. Please try again.";
            }

            return View("Delete", quiz);
        }

        [Authorize(Roles = "Edit")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quiz = await _context.Quizzes.FindAsync(id);

            if (quiz == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                _context.Quizzes.Remove(quiz);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChnagesError = true });
            }
        }

        [ExcludeFromCodeCoverage]
        private bool QuizExists(int id)
        {
            return _context.Quizzes.Any(e => e.Id == id);
        }
    }
}

WebbiSkools.QuizManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="google" content="notranslate">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebbiSkools Ltd.</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-controller="Quizzes" asp-action="Index">Quiz Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div id="navbar-collapse" class="collapse navbar-collapse justify-content-end">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <span class="text-light d-none d-md-block d-lg-block d-xl-block" data-testid="navbar-welcome-message">Hi, @User.Identity.Name!</span>
                    }
                <form class="form-inline ml-3">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-outline-light my-2 my-sm-0 text-light" asp-controller="Account" asp-action="Logout" data-testid="navbar-logout-button">Logout</a>
                    }
                    else
                    {
                        <a class="btn btn-outline-light my-2 my-sm-0 text-light" asp-controller="Account" asp-action="Login">Login</a>
                    }
                    @if (User.IsInRole("Edit"))
                    {
                        <a class="btn btn-primary ml-1 my-2 my-sm-0 text-light" asp-controller="Quizzes" asp-action="Create" data-testid="navbar-create-button">Create</a>
                    }
                </form>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="py-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>